# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# An integer n is even if, and only if, n equals twice some integer. An integer n is odd if, and only if, n equals twice some integer plus 1.
# Symbolically, if n is an integer, then
# n is even \( \Leftrightarrow \exists \) an integer k such that \(n=2k\)
# n is odd \( \Leftrightarrow \exists \) an integer k such that \(n=2k+1\)
#or n is even iff n%2==0

last_term=1
last_last_term=0

sum=0
term=0

while (term<4000000) 
  term=last_last_term+last_term
  
  if(term%2==0)
    sum=sum+term
  end
  
  last_last_term=last_term
  last_term=term
  
  
  #puts term
end

puts "\n = #{sum}"

#= 4613732


